### ISSUE TITLE
Error converting value "http://beachfrontmed..com" to type 'System.Uri'.

### ISSUE THREAD

**Issue by SimonNJensen** [builtwith/BuiltWith-C-Client-API#8]
Newtonsoft.Json.JsonSerializationException: Error converting value "http://beachfrontmed..com" to type 'System.Uri'. Path 'Results[0].Result.Paths[0].Technologies[224].Link', line 1, position 64458. ---> System.ArgumentException: Could not cast or convert from System.String to System.Uri.

**Comment by builtwith** [comment]
Thank you will be fixed in 72 hours when cache updates.
